' <auto-generated>
'     Generated by tools/gen-vectors.mjs — DO NOT EDIT BY HAND.
'
'     Every value below was recomputed from first principles and asserted
'     against the constant published in the source document before being
'     written out. Regenerate with:  node tools/gen-vectors.mjs
'
'     Sources: RFC 5869 A.1-A.3, RFC 7748 5.2/6.1, RFC 8448 3,
'              NIST CAVS AES-GCM.
' </auto-generated>

Namespace CryptoTests

    ''' <summary>Verified known-answer vectors shared by the crypto tests.</summary>
    ''' <remarks>
    ''' The values are INSTANCE fields, so the smoke tests in this same assembly
    ''' must be able to construct the class. A Private constructor made every
    ''' `New Vectors()` unbuildable, which nobody noticed while the file had no
    ''' consumer. Friend keeps it out of every other assembly.
    ''' </remarks>
    Friend NotInheritable Class Vectors

        Friend Sub New()
        End Sub

    Public ReadOnly HkdfCase1Ikm As Byte() = New Byte() { _
        &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, _
        &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B}
    Public ReadOnly HkdfCase1Salt As Byte() = New Byte() { _
        &H00, &H01, &H02, &H03, &H04, &H05, &H06, &H07, &H08, &H09, &H0A, &H0B, _
        &H0C}
    Public ReadOnly HkdfCase1Info As Byte() = {&HF0, &HF1, &HF2, &HF3, &HF4, &HF5, &HF6, &HF7, &HF8, &HF9}
    Public ReadOnly HkdfCase1Prk As Byte() = New Byte() { _
        &H07, &H77, &H09, &H36, &H2C, &H2E, &H32, &HDF, &H0D, &HDC, &H3F, &H0D, _
        &HC4, &H7B, &HBA, &H63, &H90, &HB6, &HC7, &H3B, &HB5, &H0F, &H9C, &H31, _
        &H22, &HEC, &H84, &H4A, &HD7, &HC2, &HB3, &HE5}
    Public ReadOnly HkdfCase1Okm As Byte() = New Byte() { _
        &H3C, &HB2, &H5F, &H25, &HFA, &HAC, &HD5, &H7A, &H90, &H43, &H4F, &H64, _
        &HD0, &H36, &H2F, &H2A, &H2D, &H2D, &H0A, &H90, &HCF, &H1A, &H5A, &H4C, _
        &H5D, &HB0, &H2D, &H56, &HEC, &HC4, &HC5, &HBF, &H34, &H00, &H72, &H08, _
        &HD5, &HB8, &H87, &H18, &H58, &H65}
    Public ReadOnly HkdfCase1L As Integer = 42

    Public ReadOnly HkdfCase2Ikm As Byte() = New Byte() { _
        &H00, &H01, &H02, &H03, &H04, &H05, &H06, &H07, &H08, &H09, &H0A, &H0B, _
        &H0C, &H0D, &H0E, &H0F, &H10, &H11, &H12, &H13, &H14, &H15, &H16, &H17, _
        &H18, &H19, &H1A, &H1B, &H1C, &H1D, &H1E, &H1F, &H20, &H21, &H22, &H23, _
        &H24, &H25, &H26, &H27, &H28, &H29, &H2A, &H2B, &H2C, &H2D, &H2E, &H2F, _
        &H30, &H31, &H32, &H33, &H34, &H35, &H36, &H37, &H38, &H39, &H3A, &H3B, _
        &H3C, &H3D, &H3E, &H3F, &H40, &H41, &H42, &H43, &H44, &H45, &H46, &H47, _
        &H48, &H49, &H4A, &H4B, &H4C, &H4D, &H4E, &H4F}
    Public ReadOnly HkdfCase2Salt As Byte() = New Byte() { _
        &H60, &H61, &H62, &H63, &H64, &H65, &H66, &H67, &H68, &H69, &H6A, &H6B, _
        &H6C, &H6D, &H6E, &H6F, &H70, &H71, &H72, &H73, &H74, &H75, &H76, &H77, _
        &H78, &H79, &H7A, &H7B, &H7C, &H7D, &H7E, &H7F, &H80, &H81, &H82, &H83, _
        &H84, &H85, &H86, &H87, &H88, &H89, &H8A, &H8B, &H8C, &H8D, &H8E, &H8F, _
        &H90, &H91, &H92, &H93, &H94, &H95, &H96, &H97, &H98, &H99, &H9A, &H9B, _
        &H9C, &H9D, &H9E, &H9F, &HA0, &HA1, &HA2, &HA3, &HA4, &HA5, &HA6, &HA7, _
        &HA8, &HA9, &HAA, &HAB, &HAC, &HAD, &HAE, &HAF}
    Public ReadOnly HkdfCase2Info As Byte() = New Byte() { _
        &HB0, &HB1, &HB2, &HB3, &HB4, &HB5, &HB6, &HB7, &HB8, &HB9, &HBA, &HBB, _
        &HBC, &HBD, &HBE, &HBF, &HC0, &HC1, &HC2, &HC3, &HC4, &HC5, &HC6, &HC7, _
        &HC8, &HC9, &HCA, &HCB, &HCC, &HCD, &HCE, &HCF, &HD0, &HD1, &HD2, &HD3, _
        &HD4, &HD5, &HD6, &HD7, &HD8, &HD9, &HDA, &HDB, &HDC, &HDD, &HDE, &HDF, _
        &HE0, &HE1, &HE2, &HE3, &HE4, &HE5, &HE6, &HE7, &HE8, &HE9, &HEA, &HEB, _
        &HEC, &HED, &HEE, &HEF, &HF0, &HF1, &HF2, &HF3, &HF4, &HF5, &HF6, &HF7, _
        &HF8, &HF9, &HFA, &HFB, &HFC, &HFD, &HFE, &HFF}
    Public ReadOnly HkdfCase2Prk As Byte() = New Byte() { _
        &H06, &HA6, &HB8, &H8C, &H58, &H53, &H36, &H1A, &H06, &H10, &H4C, &H9C, _
        &HEB, &H35, &HB4, &H5C, &HEF, &H76, &H00, &H14, &H90, &H46, &H71, &H01, _
        &H4A, &H19, &H3F, &H40, &HC1, &H5F, &HC2, &H44}
    Public ReadOnly HkdfCase2Okm As Byte() = New Byte() { _
        &HB1, &H1E, &H39, &H8D, &HC8, &H03, &H27, &HA1, &HC8, &HE7, &HF7, &H8C, _
        &H59, &H6A, &H49, &H34, &H4F, &H01, &H2E, &HDA, &H2D, &H4E, &HFA, &HD8, _
        &HA0, &H50, &HCC, &H4C, &H19, &HAF, &HA9, &H7C, &H59, &H04, &H5A, &H99, _
        &HCA, &HC7, &H82, &H72, &H71, &HCB, &H41, &HC6, &H5E, &H59, &H0E, &H09, _
        &HDA, &H32, &H75, &H60, &H0C, &H2F, &H09, &HB8, &H36, &H77, &H93, &HA9, _
        &HAC, &HA3, &HDB, &H71, &HCC, &H30, &HC5, &H81, &H79, &HEC, &H3E, &H87, _
        &HC1, &H4C, &H01, &HD5, &HC1, &HF3, &H43, &H4F, &H1D, &H87}
    Public ReadOnly HkdfCase2L As Integer = 82

    Public ReadOnly HkdfCase3Ikm As Byte() = New Byte() { _
        &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, _
        &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B, &H0B}
    Public ReadOnly HkdfCase3Salt As Byte() = New Byte() {}
    Public ReadOnly HkdfCase3Info As Byte() = New Byte() {}
    Public ReadOnly HkdfCase3Prk As Byte() = New Byte() { _
        &H19, &HEF, &H24, &HA3, &H2C, &H71, &H7B, &H16, &H7F, &H33, &HA9, &H1D, _
        &H6F, &H64, &H8B, &HDF, &H96, &H59, &H67, &H76, &HAF, &HDB, &H63, &H77, _
        &HAC, &H43, &H4C, &H1C, &H29, &H3C, &HCB, &H04}
    Public ReadOnly HkdfCase3Okm As Byte() = New Byte() { _
        &H8D, &HA4, &HE7, &H75, &HA5, &H63, &HC1, &H8F, &H71, &H5F, &H80, &H2A, _
        &H06, &H3C, &H5A, &H31, &HB8, &HA1, &H1F, &H5C, &H5E, &HE1, &H87, &H9E, _
        &HC3, &H45, &H4E, &H5F, &H3C, &H73, &H8D, &H2D, &H9D, &H20, &H13, &H95, _
        &HFA, &HA4, &HB6, &H1A, &H96, &HC8}
    Public ReadOnly HkdfCase3L As Integer = 42

    Public ReadOnly X25519AlicePriv As Byte() = New Byte() { _
        &H77, &H07, &H6D, &H0A, &H73, &H18, &HA5, &H7D, &H3C, &H16, &HC1, &H72, _
        &H51, &HB2, &H66, &H45, &HDF, &H4C, &H2F, &H87, &HEB, &HC0, &H99, &H2A, _
        &HB1, &H77, &HFB, &HA5, &H1D, &HB9, &H2C, &H2A}
    Public ReadOnly X25519AlicePub As Byte() = New Byte() { _
        &H85, &H20, &HF0, &H09, &H89, &H30, &HA7, &H54, &H74, &H8B, &H7D, &HDC, _
        &HB4, &H3E, &HF7, &H5A, &H0D, &HBF, &H3A, &H0D, &H26, &H38, &H1A, &HF4, _
        &HEB, &HA4, &HA9, &H8E, &HAA, &H9B, &H4E, &H6A}
    Public ReadOnly X25519BobPriv As Byte() = New Byte() { _
        &H5D, &HAB, &H08, &H7E, &H62, &H4A, &H8A, &H4B, &H79, &HE1, &H7F, &H8B, _
        &H83, &H80, &H0E, &HE6, &H6F, &H3B, &HB1, &H29, &H26, &H18, &HB6, &HFD, _
        &H1C, &H2F, &H8B, &H27, &HFF, &H88, &HE0, &HEB}
    Public ReadOnly X25519BobPub As Byte() = New Byte() { _
        &HDE, &H9E, &HDB, &H7D, &H7B, &H7D, &HC1, &HB4, &HD3, &H5B, &H61, &HC2, _
        &HEC, &HE4, &H35, &H37, &H3F, &H83, &H43, &HC8, &H5B, &H78, &H67, &H4D, _
        &HAD, &HFC, &H7E, &H14, &H6F, &H88, &H2B, &H4F}
    Public ReadOnly X25519Shared As Byte() = New Byte() { _
        &H4A, &H5D, &H9D, &H5B, &HA4, &HCE, &H2D, &HE1, &H72, &H8E, &H3B, &HF4, _
        &H80, &H35, &H0F, &H25, &HE0, &H7E, &H21, &HC9, &H47, &HD1, &H9E, &H33, _
        &H76, &HF0, &H9B, &H3C, &H1E, &H16, &H17, &H42}
    Public ReadOnly X25519IterScalar As Byte() = New Byte() { _
        &HA5, &H46, &HE3, &H6B, &HF0, &H52, &H7C, &H9D, &H3B, &H16, &H15, &H4B, _
        &H82, &H46, &H5E, &HDD, &H62, &H14, &H4C, &H0A, &HC1, &HFC, &H5A, &H18, _
        &H50, &H6A, &H22, &H44, &HBA, &H44, &H9A, &HC4}
    Public ReadOnly X25519IterU As Byte() = New Byte() { _
        &HE6, &HDB, &H68, &H67, &H58, &H30, &H30, &HDB, &H35, &H94, &HC1, &HA4, _
        &H24, &HB1, &H5F, &H7C, &H72, &H66, &H24, &HEC, &H26, &HB3, &H35, &H3B, _
        &H10, &HA9, &H03, &HA6, &HD0, &HAB, &H1C, &H4C}
    Public ReadOnly X25519IterOut As Byte() = New Byte() { _
        &HC3, &HDA, &H55, &H37, &H9D, &HE9, &HC6, &H90, &H8E, &H94, &HEA, &H4D, _
        &HF2, &H8D, &H08, &H4F, &H32, &HEC, &HCF, &H03, &H49, &H1C, &H71, &HF7, _
        &H54, &HB4, &H07, &H55, &H77, &HA2, &H85, &H52}

    Public ReadOnly AesGcmKey128 As Byte() = New Byte() { _
        &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, _
        &H00, &H00, &H00, &H00}
    Public ReadOnly AesGcmKey256 As Byte() = New Byte() { _
        &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, _
        &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, _
        &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00}
    Public ReadOnly AesGcmIv As Byte() = {&H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00, &H00}
    Public ReadOnly AesGcmEmptyTag128 As Byte() = New Byte() { _
        &H58, &HE2, &HFC, &HCE, &HFA, &H7E, &H30, &H61, &H36, &H7F, &H1D, &H57, _
        &HA4, &HE7, &H45, &H5A}
    Public ReadOnly AesGcmBlockCt128 As Byte() = New Byte() { _
        &H03, &H88, &HDA, &HCE, &H60, &HB6, &HA3, &H92, &HF3, &H28, &HC2, &HB9, _
        &H71, &HB2, &HFE, &H78}
    Public ReadOnly AesGcmBlockTag128 As Byte() = New Byte() { _
        &HAB, &H6E, &H47, &HD4, &H2C, &HEC, &H13, &HBD, &HF5, &H3A, &H67, &HB2, _
        &H12, &H57, &HBD, &HDF}
    Public ReadOnly AesGcmEmptyTag256 As Byte() = New Byte() { _
        &H53, &H0F, &H8A, &HFB, &HC7, &H45, &H36, &HB9, &HA9, &H63, &HB4, &HF1, _
        &HC4, &HCB, &H73, &H8B}

    Public ReadOnly Tls13ClientPriv As Byte() = New Byte() { _
        &H49, &HAF, &H42, &HBA, &H7F, &H79, &H94, &H85, &H2D, &H71, &H3E, &HF2, _
        &H78, &H4B, &HCB, &HCA, &HA7, &H91, &H1D, &HE2, &H6A, &HDC, &H56, &H42, _
        &HCB, &H63, &H45, &H40, &HE7, &HEA, &H50, &H05}
    Public ReadOnly Tls13ClientPub As Byte() = New Byte() { _
        &H99, &H38, &H1D, &HE5, &H60, &HE4, &HBD, &H43, &HD2, &H3D, &H8E, &H43, _
        &H5A, &H7D, &HBA, &HFE, &HB3, &HC0, &H6E, &H51, &HC1, &H3C, &HAE, &H4D, _
        &H54, &H13, &H69, &H1E, &H52, &H9A, &HAF, &H2C}
    Public ReadOnly Tls13ServerPriv As Byte() = New Byte() { _
        &HB1, &H58, &H0E, &HEA, &HDF, &H6D, &HD5, &H89, &HB8, &HEF, &H4F, &H2D, _
        &H56, &H52, &H57, &H8C, &HC8, &H10, &HE9, &H98, &H01, &H91, &HEC, &H8D, _
        &H05, &H83, &H08, &HCE, &HA2, &H16, &HA2, &H1E}
    Public ReadOnly Tls13ServerPub As Byte() = New Byte() { _
        &HC9, &H82, &H88, &H76, &H11, &H20, &H95, &HFE, &H66, &H76, &H2B, &HDB, _
        &HF7, &HC6, &H72, &HE1, &H56, &HD6, &HCC, &H25, &H3B, &H83, &H3D, &HF1, _
        &HDD, &H69, &HB1, &HB0, &H4E, &H75, &H1F, &H0F}
    Public ReadOnly Tls13Ecdhe As Byte() = New Byte() { _
        &H8B, &HD4, &H05, &H4F, &HB5, &H5B, &H9D, &H63, &HFD, &HFB, &HAC, &HF9, _
        &HF0, &H4B, &H9F, &H0D, &H35, &HE6, &HD6, &H3F, &H53, &H75, &H63, &HEF, _
        &HD4, &H62, &H72, &H90, &H0F, &H89, &H49, &H2D}
    Public ReadOnly Tls13EarlySecret As Byte() = New Byte() { _
        &H33, &HAD, &H0A, &H1C, &H60, &H7E, &HC0, &H3B, &H09, &HE6, &HCD, &H98, _
        &H93, &H68, &H0C, &HE2, &H10, &HAD, &HF3, &H00, &HAA, &H1F, &H26, &H60, _
        &HE1, &HB2, &H2E, &H10, &HF1, &H70, &HF9, &H2A}
    Public ReadOnly Tls13DerivedEarly As Byte() = New Byte() { _
        &H6F, &H26, &H15, &HA1, &H08, &HC7, &H02, &HC5, &H67, &H8F, &H54, &HFC, _
        &H9D, &HBA, &HB6, &H97, &H16, &HC0, &H76, &H18, &H9C, &H48, &H25, &H0C, _
        &HEB, &HEA, &HC3, &H57, &H6C, &H36, &H11, &HBA}
    Public ReadOnly Tls13HandshakeSecret As Byte() = New Byte() { _
        &H1D, &HC8, &H26, &HE9, &H36, &H06, &HAA, &H6F, &HDC, &H0A, &HAD, &HC1, _
        &H2F, &H74, &H1B, &H01, &H04, &H6A, &HA6, &HB9, &H9F, &H69, &H1E, &HD2, _
        &H21, &HA9, &HF0, &HCA, &H04, &H3F, &HBE, &HAC}
    Public ReadOnly Tls13TranscriptChSh As Byte() = New Byte() { _
        &H86, &H0C, &H06, &HED, &HC0, &H78, &H58, &HEE, &H8E, &H78, &HF0, &HE7, _
        &H42, &H8C, &H58, &HED, &HD6, &HB4, &H3F, &H2C, &HA3, &HE6, &HE9, &H5F, _
        &H02, &HED, &H06, &H3C, &HF0, &HE1, &HCA, &HD8}
    Public ReadOnly Tls13ClientHsTraffic As Byte() = New Byte() { _
        &HB3, &HED, &HDB, &H12, &H6E, &H06, &H7F, &H35, &HA7, &H80, &HB3, &HAB, _
        &HF4, &H5E, &H2D, &H8F, &H3B, &H1A, &H95, &H07, &H38, &HF5, &H2E, &H96, _
        &H00, &H74, &H6A, &H0E, &H27, &HA5, &H5A, &H21}
    Public ReadOnly Tls13ServerHsTraffic As Byte() = New Byte() { _
        &HB6, &H7B, &H7D, &H69, &H0C, &HC1, &H6C, &H4E, &H75, &HE5, &H42, &H13, _
        &HCB, &H2D, &H37, &HB4, &HE9, &HC9, &H12, &HBC, &HDE, &HD9, &H10, &H5D, _
        &H42, &HBE, &HFD, &H59, &HD3, &H91, &HAD, &H38}
    Public ReadOnly Tls13ServerHsKey As Byte() = New Byte() { _
        &H3F, &HCE, &H51, &H60, &H09, &HC2, &H17, &H27, &HD0, &HF2, &HE4, &HE8, _
        &H6E, &HE4, &H03, &HBC}
    Public ReadOnly Tls13ServerHsIv As Byte() = {&H5D, &H31, &H3E, &HB2, &H67, &H12, &H76, &HEE, &H13, &H00, &H0B, &H30}
    Public ReadOnly Tls13DerivedMaster As Byte() = New Byte() { _
        &H43, &HDE, &H77, &HE0, &HC7, &H77, &H13, &H85, &H9A, &H94, &H4D, &HB9, _
        &HDB, &H25, &H90, &HB5, &H31, &H90, &HA6, &H5B, &H3E, &HE2, &HE4, &HF1, _
        &H2D, &HD7, &HA0, &HBB, &H7C, &HE2, &H54, &HB4}
    Public ReadOnly Tls13MasterSecret As Byte() = New Byte() { _
        &H18, &HDF, &H06, &H84, &H3D, &H13, &HA0, &H8B, &HF2, &HA4, &H49, &H84, _
        &H4C, &H5F, &H8A, &H47, &H80, &H01, &HBC, &H4D, &H4C, &H62, &H79, &H84, _
        &HD5, &HA4, &H1D, &HA8, &HD0, &H40, &H29, &H19}
    Public ReadOnly Tls13TranscriptChSf As Byte() = New Byte() { _
        &H96, &H08, &H10, &H2A, &H0F, &H1C, &HCC, &H6D, &HB6, &H25, &H0B, &H7B, _
        &H7E, &H41, &H7B, &H1A, &H00, &H0E, &HAA, &HDA, &H3D, &HAA, &HE4, &H77, _
        &H7A, &H76, &H86, &HC9, &HFF, &H83, &HDF, &H13}
    Public ReadOnly Tls13ClientApTraffic As Byte() = New Byte() { _
        &H9E, &H40, &H64, &H6C, &HE7, &H9A, &H7F, &H9D, &HC0, &H5A, &HF8, &H88, _
        &H9B, &HCE, &H65, &H52, &H87, &H5A, &HFA, &H0B, &H06, &HDF, &H00, &H87, _
        &HF7, &H92, &HEB, &HB7, &HC1, &H75, &H04, &HA5}
    Public ReadOnly Tls13ServerApTraffic As Byte() = New Byte() { _
        &HA1, &H1A, &HF9, &HF0, &H55, &H31, &HF8, &H56, &HAD, &H47, &H11, &H6B, _
        &H45, &HA9, &H50, &H32, &H82, &H04, &HB4, &HF4, &H4B, &HFB, &H6B, &H3A, _
        &H4B, &H4F, &H1F, &H3F, &HCB, &H63, &H16, &H43}
    Public ReadOnly Tls13ServerFinishedKey As Byte() = New Byte() { _
        &H00, &H8D, &H3B, &H66, &HF8, &H16, &HEA, &H55, &H9F, &H96, &HB5, &H37, _
        &HE8, &H85, &HC3, &H1F, &HC0, &H68, &HBF, &H49, &H2C, &H65, &H2F, &H01, _
        &HF2, &H88, &HA1, &HD8, &HCD, &HC1, &H9F, &HC8}
    Public ReadOnly Tls13ServerFinished As Byte() = New Byte() { _
        &H9B, &H9B, &H14, &H1D, &H90, &H63, &H37, &HFB, &HD2, &HCB, &HDC, &HE7, _
        &H1D, &HF4, &HDE, &HDA, &H4A, &HB4, &H2C, &H30, &H95, &H72, &HCB, &H7F, _
        &HFF, &HEE, &H54, &H54, &HB7, &H8F, &H07, &H18}
    Public ReadOnly Tls13ExporterMasterSecret As Byte() = New Byte() { _
        &HFE, &H22, &HF8, &H81, &H17, &H6E, &HDA, &H18, &HEB, &H8F, &H44, &H52, _
        &H9E, &H67, &H92, &HC5, &H0C, &H9A, &H3F, &H89, &H45, &H2F, &H68, &HD8, _
        &HAE, &H31, &H1B, &H43, &H09, &HD3, &HCF, &H50}
    Public ReadOnly Tls13MsgClientHello As Byte() = New Byte() { _
        &H01, &H00, &H00, &HC0, &H03, &H03, &HCB, &H34, &HEC, &HB1, &HE7, &H81, _
        &H63, &HBA, &H1C, &H38, &HC6, &HDA, &HCB, &H19, &H6A, &H6D, &HFF, &HA2, _
        &H1A, &H8D, &H99, &H12, &HEC, &H18, &HA2, &HEF, &H62, &H83, &H02, &H4D, _
        &HEC, &HE7, &H00, &H00, &H06, &H13, &H01, &H13, &H03, &H13, &H02, &H01, _
        &H00, &H00, &H91, &H00, &H00, &H00, &H0B, &H00, &H09, &H00, &H00, &H06, _
        &H73, &H65, &H72, &H76, &H65, &H72, &HFF, &H01, &H00, &H01, &H00, &H00, _
        &H0A, &H00, &H14, &H00, &H12, &H00, &H1D, &H00, &H17, &H00, &H18, &H00, _
        &H19, &H01, &H00, &H01, &H01, &H01, &H02, &H01, &H03, &H01, &H04, &H00, _
        &H23, &H00, &H00, &H00, &H33, &H00, &H26, &H00, &H24, &H00, &H1D, &H00, _
        &H20, &H99, &H38, &H1D, &HE5, &H60, &HE4, &HBD, &H43, &HD2, &H3D, &H8E, _
        &H43, &H5A, &H7D, &HBA, &HFE, &HB3, &HC0, &H6E, &H51, &HC1, &H3C, &HAE, _
        &H4D, &H54, &H13, &H69, &H1E, &H52, &H9A, &HAF, &H2C, &H00, &H2B, &H00, _
        &H03, &H02, &H03, &H04, &H00, &H0D, &H00, &H20, &H00, &H1E, &H04, &H03, _
        &H05, &H03, &H06, &H03, &H02, &H03, &H08, &H04, &H08, &H05, &H08, &H06, _
        &H04, &H01, &H05, &H01, &H06, &H01, &H02, &H01, &H04, &H02, &H05, &H02, _
        &H06, &H02, &H02, &H02, &H00, &H2D, &H00, &H02, &H01, &H01, &H00, &H1C, _
        &H00, &H02, &H40, &H01}
    Public ReadOnly Tls13MsgServerHello As Byte() = New Byte() { _
        &H02, &H00, &H00, &H56, &H03, &H03, &HA6, &HAF, &H06, &HA4, &H12, &H18, _
        &H60, &HDC, &H5E, &H6E, &H60, &H24, &H9C, &HD3, &H4C, &H95, &H93, &H0C, _
        &H8A, &HC5, &HCB, &H14, &H34, &HDA, &HC1, &H55, &H77, &H2E, &HD3, &HE2, _
        &H69, &H28, &H00, &H13, &H01, &H00, &H00, &H2E, &H00, &H33, &H00, &H24, _
        &H00, &H1D, &H00, &H20, &HC9, &H82, &H88, &H76, &H11, &H20, &H95, &HFE, _
        &H66, &H76, &H2B, &HDB, &HF7, &HC6, &H72, &HE1, &H56, &HD6, &HCC, &H25, _
        &H3B, &H83, &H3D, &HF1, &HDD, &H69, &HB1, &HB0, &H4E, &H75, &H1F, &H0F, _
        &H00, &H2B, &H00, &H02, &H03, &H04}
    Public ReadOnly Tls13MsgEncryptedExtensions As Byte() = New Byte() { _
        &H08, &H00, &H00, &H24, &H00, &H22, &H00, &H0A, &H00, &H14, &H00, &H12, _
        &H00, &H1D, &H00, &H17, &H00, &H18, &H00, &H19, &H01, &H00, &H01, &H01, _
        &H01, &H02, &H01, &H03, &H01, &H04, &H00, &H1C, &H00, &H02, &H40, &H01, _
        &H00, &H00, &H00, &H00}
    Public ReadOnly Tls13MsgCertificate As Byte() = New Byte() { _
        &H0B, &H00, &H01, &HB9, &H00, &H00, &H01, &HB5, &H00, &H01, &HB0, &H30, _
        &H82, &H01, &HAC, &H30, &H82, &H01, &H15, &HA0, &H03, &H02, &H01, &H02, _
        &H02, &H01, &H02, &H30, &H0D, &H06, &H09, &H2A, &H86, &H48, &H86, &HF7, _
        &H0D, &H01, &H01, &H0B, &H05, &H00, &H30, &H0E, &H31, &H0C, &H30, &H0A, _
        &H06, &H03, &H55, &H04, &H03, &H13, &H03, &H72, &H73, &H61, &H30, &H1E, _
        &H17, &H0D, &H31, &H36, &H30, &H37, &H33, &H30, &H30, &H31, &H32, &H33, _
        &H35, &H39, &H5A, &H17, &H0D, &H32, &H36, &H30, &H37, &H33, &H30, &H30, _
        &H31, &H32, &H33, &H35, &H39, &H5A, &H30, &H0E, &H31, &H0C, &H30, &H0A, _
        &H06, &H03, &H55, &H04, &H03, &H13, &H03, &H72, &H73, &H61, &H30, &H81, _
        &H9F, &H30, &H0D, &H06, &H09, &H2A, &H86, &H48, &H86, &HF7, &H0D, &H01, _
        &H01, &H01, &H05, &H00, &H03, &H81, &H8D, &H00, &H30, &H81, &H89, &H02, _
        &H81, &H81, &H00, &HB4, &HBB, &H49, &H8F, &H82, &H79, &H30, &H3D, &H98, _
        &H08, &H36, &H39, &H9B, &H36, &HC6, &H98, &H8C, &H0C, &H68, &HDE, &H55, _
        &HE1, &HBD, &HB8, &H26, &HD3, &H90, &H1A, &H24, &H61, &HEA, &HFD, &H2D, _
        &HE4, &H9A, &H91, &HD0, &H15, &HAB, &HBC, &H9A, &H95, &H13, &H7A, &HCE, _
        &H6C, &H1A, &HF1, &H9E, &HAA, &H6A, &HF9, &H8C, &H7C, &HED, &H43, &H12, _
        &H09, &H98, &HE1, &H87, &HA8, &H0E, &HE0, &HCC, &HB0, &H52, &H4B, &H1B, _
        &H01, &H8C, &H3E, &H0B, &H63, &H26, &H4D, &H44, &H9A, &H6D, &H38, &HE2, _
        &H2A, &H5F, &HDA, &H43, &H08, &H46, &H74, &H80, &H30, &H53, &H0E, &HF0, _
        &H46, &H1C, &H8C, &HA9, &HD9, &HEF, &HBF, &HAE, &H8E, &HA6, &HD1, &HD0, _
        &H3E, &H2B, &HD1, &H93, &HEF, &HF0, &HAB, &H9A, &H80, &H02, &HC4, &H74, _
        &H28, &HA6, &HD3, &H5A, &H8D, &H88, &HD7, &H9F, &H7F, &H1E, &H3F, &H02, _
        &H03, &H01, &H00, &H01, &HA3, &H1A, &H30, &H18, &H30, &H09, &H06, &H03, _
        &H55, &H1D, &H13, &H04, &H02, &H30, &H00, &H30, &H0B, &H06, &H03, &H55, _
        &H1D, &H0F, &H04, &H04, &H03, &H02, &H05, &HA0, &H30, &H0D, &H06, &H09, _
        &H2A, &H86, &H48, &H86, &HF7, &H0D, &H01, &H01, &H0B, &H05, &H00, &H03, _
        &H81, &H81, &H00, &H85, &HAA, &HD2, &HA0, &HE5, &HB9, &H27, &H6B, &H90, _
        &H8C, &H65, &HF7, &H3A, &H72, &H67, &H17, &H06, &H18, &HA5, &H4C, &H5F, _
        &H8A, &H7B, &H33, &H7D, &H2D, &HF7, &HA5, &H94, &H36, &H54, &H17, &HF2, _
        &HEA, &HE8, &HF8, &HA5, &H8C, &H8F, &H81, &H72, &HF9, &H31, &H9C, &HF3, _
        &H6B, &H7F, &HD6, &HC5, &H5B, &H80, &HF2, &H1A, &H03, &H01, &H51, &H56, _
        &H72, &H60, &H96, &HFD, &H33, &H5E, &H5E, &H67, &HF2, &HDB, &HF1, &H02, _
        &H70, &H2E, &H60, &H8C, &HCA, &HE6, &HBE, &HC1, &HFC, &H63, &HA4, &H2A, _
        &H99, &HBE, &H5C, &H3E, &HB7, &H10, &H7C, &H3C, &H54, &HE9, &HB9, &HEB, _
        &H2B, &HD5, &H20, &H3B, &H1C, &H3B, &H84, &HE0, &HA8, &HB2, &HF7, &H59, _
        &H40, &H9B, &HA3, &HEA, &HC9, &HD9, &H1D, &H40, &H2D, &HCC, &H0C, &HC8, _
        &HF8, &H96, &H12, &H29, &HAC, &H91, &H87, &HB4, &H2B, &H4D, &HE1, &H00, _
        &H00}
    Public ReadOnly Tls13MsgCertificateVerify As Byte() = New Byte() { _
        &H0F, &H00, &H00, &H84, &H08, &H04, &H00, &H80, &H5A, &H74, &H7C, &H5D, _
        &H88, &HFA, &H9B, &HD2, &HE5, &H5A, &HB0, &H85, &HA6, &H10, &H15, &HB7, _
        &H21, &H1F, &H82, &H4C, &HD4, &H84, &H14, &H5A, &HB3, &HFF, &H52, &HF1, _
        &HFD, &HA8, &H47, &H7B, &H0B, &H7A, &HBC, &H90, &HDB, &H78, &HE2, &HD3, _
        &H3A, &H5C, &H14, &H1A, &H07, &H86, &H53, &HFA, &H6B, &HEF, &H78, &H0C, _
        &H5E, &HA2, &H48, &HEE, &HAA, &HA7, &H85, &HC4, &HF3, &H94, &HCA, &HB6, _
        &HD3, &H0B, &HBE, &H8D, &H48, &H59, &HEE, &H51, &H1F, &H60, &H29, &H57, _
        &HB1, &H54, &H11, &HAC, &H02, &H76, &H71, &H45, &H9E, &H46, &H44, &H5C, _
        &H9E, &HA5, &H8C, &H18, &H1E, &H81, &H8E, &H95, &HB8, &HC3, &HFB, &H0B, _
        &HF3, &H27, &H84, &H09, &HD3, &HBE, &H15, &H2A, &H3D, &HA5, &H04, &H3E, _
        &H06, &H3D, &HDA, &H65, &HCD, &HF5, &HAE, &HA2, &H0D, &H53, &HDF, &HAC, _
        &HD4, &H2F, &H74, &HF3}
    Public ReadOnly Tls13MsgFinished As Byte() = New Byte() { _
        &H14, &H00, &H00, &H20, &H9B, &H9B, &H14, &H1D, &H90, &H63, &H37, &HFB, _
        &HD2, &HCB, &HDC, &HE7, &H1D, &HF4, &HDE, &HDA, &H4A, &HB4, &H2C, &H30, _
        &H95, &H72, &HCB, &H7F, &HFF, &HEE, &H54, &H54, &HB7, &H8F, &H07, &H18}

    End Class

End Namespace
